name: hello-world
on: [push]
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
